#!/bin/bash
cd ./buildroot
if [ $? -ne 0 ]; then
  echo "Failed to change directory to ./buildroot."
  exit 1
fi

make BR2_EXTERNAL=../hifiberry-os/buildroot/ menuconfig
if [ $? -ne 0 ]; then
  echo "Make menuconfig failed."
  exit 1
fi
