#!/bin/bash

BUSYBOX_URL="https://busybox.net/downloads/"
BUSYBOX_VERSION="busybox-1.36.1"
export ARCH="arm"
export CROSS_COMPILE="arm-none-linux-gnueabihf-"
export PATH=../../ti-sdk/external-toolchain-dir/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/bin/:$PATH

cd ./initramfs/

wget "${BUSYBOX_URL}${BUSYBOX_VERSION}.tar.bz2"
tar -xf ./${BUSYBOX_VERSION}.tar.bz2

rm ${BUSYBOX_VERSION}.tar.bz2
cd ./${BUSYBOX_VERSION}

make clean
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf- defconfig

sed -i 's/^# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
sed -i 's/^CONFIG_STATIC=n/CONFIG_STATIC=y/' .config

make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf-
make install CONFIG_PREFIX=../../output/initramfs


cd ../../output/initramfs
cp -r ../../overlay/initramfs/* ./
sudo mknod ../../output/initramfs/dev/console c 5 1

find . | cpio -o -H newc | gzip > ../initramfs.cpio.gz
