#!/bin/sh

# Check if the buildroot directory exists
if [ -d "./buildroot" ]; then
    echo "Changing directory to buildroot..."
    cd buildroot
    make clean
fi

if [ -d "./buildroot" ]; then
    echo "Changing directory to buildroot..."
    cd buildroot
    make clean
fi

